
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 889901
	#The name of the modpack
	modpackName = "Enlightened 6 Expert"
	#The version of the modpack
	modpackVersion = "2.8.0"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

