name: Prettier

on:
  workflow_dispatch:

  push:
    branches:
      - 'enlightened_master'
      # - 'enlightened_develop'
      - 'prettier-*'

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
      - uses: denoland/setup-deno@v1

      - run: npx --yes prettier -v
      - run: deno run --allow-run .github/actions/ci/prettier.ts
      - run: git pull
      - run: git push
